---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# weburl

<!-- badges: start -->
<!-- badges: end -->

`{weburl}`wraps the [Rust crate url](https://crates.io/crates/url). This package is under development.

## Installation

You can install the development version of weburl like so:

``` r
if (!requireNamespace("remotes")) install.packages("remotes")

remotes::install_github("dyfanjones/weburl")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(weburl)
urls <- c(
  "/",
  "//google.com",
  "file:///",
  "http://google.com/",
  "http://google.com/path",
  "http://google.com/path?a=1&b=2",
  "http://google.com:1234/path?a=1&b=2",
  "http://google.com:8080/path?a=1&b=2#frag",
  "http://google.com:8080/path?a=1&b=2&c=%7B1%7B2%7D3%7D#frag",
  "http://user@google.com/path?a=1&b=2",
  "http://user:pass@google.com:8000/path?a=1&b=2",
  "svn+ssh://my.svn.server/repo/trunk",
  "https://google.com:8080"
)

```

Parse all Urls into a data.frame

```{r parse_example}
url_parse(urls)
```

Get Url elements:
```{r get_example}
get_scheme(urls)
get_host(urls)
get_port(urls)
get_query(urls)
get_path(urls)
get_fragment(urls)
get_username(urls)
get_password(urls)
```

Set Url elements:
```{r set example}
set_scheme(urls, "https")
set_host(urls, "helloworld")
set_port(urls, 8080)
set_query(urls, list("foo" = "bar=yo"))
set_path(urls, c("path", "to", "somewhere"))
set_fragment(urls, "cell=4,1-6,2")
set_username(urls, "foo")
set_password(urls, "bar")
```

Building Url by piping:
```{r piping example}
url <- "http://example.com"

set_scheme(url, "https") |>
  set_port(1234) |>
  set_path(c("foo", "bar")) |>
  set_query("baz") |>
  set_fragment("quux") |>
  set_username("user") |>
  set_password("pass")
```

Url encoding:
```{r encode example}
url_encode("https://example.com/?country=español")
```


