# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_weburl_wrappers", use_symbols = TRUE, package_name = "weburl")

#' @docType package
#' @usage NULL
#' @useDynLib weburl, .registration = TRUE
NULL

#' Parse url
#' @param url character vector of urls
#' @return a data.frame consisting of the columns scheme, host, port, path, query and fragment.
#' @export
url_parse <- function(url) .Call(wrap__url_parse, url)


# nolint end
